name: Release

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    id-token: write
    issues: write
    pull-requests: write

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        timeout-minutes: 15
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - name: Install dependencies
              run: npm ci

            - name: Code Quality
              run: npm run lint

            - name: Build
              run: npm run build

            - name: Tests
              run: npm run test

            - name: Publish release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release
